
try { redirector.main(); } catch (e) { console.error("An error occurred when calling (redirector/main)"); throw(e); }